#!/usr/bin/env python3
# Regenerate tools/swd_patcher/src/gold_pages.h from the stock firmware image.
# Run from the repo root:  python3 tools/swd_patcher/scripts/gen_gold_pages.py
import hashlib, pathlib, struct, binascii, sys

REPO = pathlib.Path(__file__).resolve().parents[3]
SRC  = REPO / "firmware/V1.0.03.230201/ht32_flash_64k.bin"
OUT  = REPO / "tools/swd_patcher/src/gold_pages.h"
PAGES = (0x2C00, 0x4400)  # 0xC400 is all-FF in stock, no need to embed

def main():
    img = SRC.read_bytes()
    md5 = hashlib.md5(img).hexdigest()
    lines = [
        "// AUTO-GENERATED by tools/swd_patcher/scripts/gen_gold_pages.py",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f'static constexpr const char *GOLD_FW_MD5 = "{md5}";',
        "",
    ]
    for base in PAGES:
        page = img[base:base + 0x400]
        words = struct.unpack("<256I", page)
        lines += [
            f"// Page 0x{base:04X} from ht32_flash_64k.bin (md5 {md5})",
            f"// crc32 0x{binascii.crc32(page):08X}",
            f"static const uint32_t GOLD_PAGE_{base:04X}[256] PROGMEM = {{",
        ]
        for i in range(0, 256, 8):
            chunk = ", ".join(f"0x{w:08X}" for w in words[i:i + 8])
            lines.append(f"    {chunk},")
        lines += ["};", ""]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)} lines)")

if __name__ == "__main__":
    sys.exit(main())
